// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThuHaiDuong.Infrastructure.DataContext;

#nullable disable

namespace ThuHaiDuong.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateClick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AffiliateLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ClickedAt")
                        .HasDatabaseName("IX_AffiliateClick_ClickedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AffiliateClick_UserId");

                    b.HasIndex("AffiliateLinkId", "ClickedAt")
                        .HasDatabaseName("IX_AffiliateClick_LinkId_ClickedAt");

                    b.ToTable("affiliate_clicks", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("in-chapter");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasDatabaseName("IX_AffiliateLink_TrackingCode");

                    b.HasIndex("IsActive", "Placement", "Priority")
                        .HasDatabaseName("IX_AffiliateLink_IsActive_Placement_Priority");

                    b.ToTable("affiliate_links", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateLinkChapter", b =>
                {
                    b.Property<Guid>("AffiliateLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AffiliateLinkId", "ChapterId");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("IX_AffiliateLinkChapter_ChapterId");

                    b.ToTable("affiliate_link_chapters", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateLinkStory", b =>
                {
                    b.Property<Guid>("AffiliateLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AffiliateLinkId", "StoryId");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("IX_AffiliateLinkStory_StoryId");

                    b.ToTable("affiliate_link_stories", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Country")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PenName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_Author_Country");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Author_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Author_Slug");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Bookmark_UserId_CreatedAt");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_Bookmark_UserId_StoryId");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Category_ParentId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Category_Slug");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("IX_Category_IsActive_SortOrder");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("StoryId", "ChapterNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Chapter_StoryId_ChapterNumber");

                    b.HasIndex("StoryId", "Status", "ChapterNumber")
                        .HasDatabaseName("IX_Chapter_StoryId_Status_ChapterNumber");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.ChapterView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ChapterId", "ViewedAt")
                        .HasDatabaseName("IX_ChapterView_ChapterId_ViewedAt");

                    b.HasIndex("SessionId", "ChapterId")
                        .HasDatabaseName("IX_ChapterView_SessionId_ChapterId");

                    b.HasIndex("StoryId", "ViewedAt")
                        .HasDatabaseName("IX_ChapterView_StoryId_ViewedAt");

                    b.ToTable("chapter_views", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Comment_UserId");

                    b.HasIndex("ParentCommentId", "CreatedAt")
                        .HasDatabaseName("IX_Comment_ParentCommentId_CreatedAt");

                    b.HasIndex("StoryId", "ChapterId", "CreatedAt")
                        .HasDatabaseName("IX_Comment_StoryId_ChapterId_CreatedAt");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.DailyStoryStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewBookmarks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NewRatings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UniqueVisitors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("StatDate", "ViewCount")
                        .HasDatabaseName("IX_DailyStoryStat_StatDate_ViewCount");

                    b.HasIndex("StoryId", "StatDate")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyStoryStat_StoryId_StatDate");

                    b.ToTable("daily_story_stats", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("IX_Rating_StoryId");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_Rating_UserId_StoryId");

                    b.ToTable("ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Score", "[Score] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.ReadingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId", "ChapterId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReadingHistory_UserId_ChapterId");

                    b.HasIndex("UserId", "ReadAt")
                        .HasDatabaseName("IX_ReadingHistory_UserId_ReadAt");

                    b.HasIndex("UserId", "StoryId", "ReadAt")
                        .HasDatabaseName("IX_ReadingHistory_UserId_StoryId_ReadAt");

                    b.ToTable("reading_histories", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshToken_ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshToken_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshToken_UserId");

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshToken_UserId_IsRevoked_ExpiresAt");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ContentSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manual");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastChapterAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextChapterAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReleaseSchedule")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("StoryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TotalChapters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("TotalViews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContentSource")
                        .HasDatabaseName("IX_Story_ContentSource");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Story_Slug");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("IX_Story_UploadedByUserId");

                    b.HasIndex("AuthorId", "Status")
                        .HasDatabaseName("IX_Story_AuthorId_Status");

                    b.HasIndex("Status", "LastChapterAt")
                        .HasDatabaseName("IX_Story_Status_LastChapterAt");

                    b.HasIndex("Status", "TotalViews")
                        .HasDatabaseName("IX_Story_Status_TotalViews");

                    b.HasIndex("StoryType", "NextChapterAt")
                        .HasDatabaseName("IX_Story_StoryType_NextChapterAt");

                    b.HasIndex("StoryType", "Status", "LastChapterAt")
                        .HasDatabaseName("IX_Story_StoryType_Status_LastChapterAt");

                    b.ToTable("stories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Story_ReleaseSchedule", "[ReleaseSchedule] IS NULL OR [ReleaseSchedule] IN ('Daily', 'Weekly', 'BiWeekly', 'Monthly')");

                            t.HasCheckConstraint("CK_Story_StoryType", "[StoryType] IN ('Serial', 'Completed')");
                        });
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.StoryCategory", b =>
                {
                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StoryId", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_StoryCategory_CategoryId");

                    b.ToTable("story_categories", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.StoryTag", b =>
                {
                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StoryId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_StoryTag_TagId");

                    b.ToTable("story_tags", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PendingPayment");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_Subscription_EndDate");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_Subscription_TransactionId");

                    b.HasIndex("UserId", "Status", "EndDate")
                        .HasDatabaseName("IX_Subscription_UserId_Status_EndDate");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tag_Name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tag_Slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Reader");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_User_Role");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_User_UserName");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.UserReadingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LastChapterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LastChapterId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId", "LastReadAt")
                        .HasDatabaseName("IX_UserReadingProgress_UserId_LastReadAt");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserReadingProgress_UserId_StoryId");

                    b.ToTable("user_reading_progresses", (string)null);
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateClick", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.AffiliateLink", "AffiliateLink")
                        .WithMany("AffiliateClicks")
                        .HasForeignKey("AffiliateLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Chapter", "Chapter")
                        .WithMany("AffiliateClicks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("AffiliateClicks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AffiliateLink");

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateLinkChapter", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.AffiliateLink", "AffiliateLink")
                        .WithMany("AffiliateLinkChapters")
                        .HasForeignKey("AffiliateLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliateLink");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateLinkStory", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.AffiliateLink", "AffiliateLink")
                        .WithMany("AffiliateLinkStories")
                        .HasForeignKey("AffiliateLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("AffiliateLinkStories")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AffiliateLink");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("Bookmarks")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Category", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.ChapterView", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Chapter", "Chapter")
                        .WithMany("ChapterViews")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("ChapterViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Comment", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Comments")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ThuHaiDuong.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chapter");

                    b.Navigation("ParentComment");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.DailyStoryStat", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("DailyStoryStats")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Rating", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("Ratings")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.ReadingHistory", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Story", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Author", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedStories")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.StoryCategory", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Category", "Category")
                        .WithMany("StoryCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("StoryCategories")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.StoryTag", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("StoryTags")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Tag", "Tag")
                        .WithMany("StoryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.UserReadingProgress", b =>
                {
                    b.HasOne("ThuHaiDuong.Domain.Entities.Chapter", "LastChapter")
                        .WithMany()
                        .HasForeignKey("LastChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.Story", "Story")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThuHaiDuong.Domain.Entities.User", "User")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LastChapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.AffiliateLink", b =>
                {
                    b.Navigation("AffiliateClicks");

                    b.Navigation("AffiliateLinkChapters");

                    b.Navigation("AffiliateLinkStories");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Author", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("StoryCategories");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("AffiliateClicks");

                    b.Navigation("ChapterViews");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Story", b =>
                {
                    b.Navigation("AffiliateLinkStories");

                    b.Navigation("Bookmarks");

                    b.Navigation("Chapters");

                    b.Navigation("Comments");

                    b.Navigation("DailyStoryStats");

                    b.Navigation("Ratings");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("StoryCategories");

                    b.Navigation("StoryTags");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.Tag", b =>
                {
                    b.Navigation("StoryTags");
                });

            modelBuilder.Entity("ThuHaiDuong.Domain.Entities.User", b =>
                {
                    b.Navigation("AffiliateClicks");

                    b.Navigation("Bookmarks");

                    b.Navigation("ChapterViews");

                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscriptions");

                    b.Navigation("UploadedStories");
                });
#pragma warning restore 612, 618
        }
    }
}
